apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-ts-k8s-webserver-deployment
spec:
  selector:
    matchLabels:
      app: node-ts-k8s-webserver
  template:
    metadata:
      labels:
        app: node-ts-k8s-webserver
    spec:
      containers:
      - name: node-ts-k8s-webserver
        image: itziksavaia/node-ts-k8s-webserver:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3002
