apiVersion: v1
kind: Service
metadata:
  name: node-ts-k8s-webserver-service
spec:
  selector:
    app: node-ts-k8s-webserver
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3002
    nodePort: 31110
